version: 3

silent: true

includes:
  ddbot:
    taskfile: ./ddbot
    dir: ./ddbot

vars:
  NENV: "node_modules"
  SERVICES: "ddbot"

tasks:
  _prettier:
    internal: true
    cmds:
      - "{{.NENV}}/.bin/prettier {{.COMMAND}}"

  _with_nvm:
    internal: true
    cmds:
      - "source ${HOME}/.nvm/nvm.sh && nvm install && {{.COMMAND}}"

  init:
    desc: Initialize project environment
    cmds:
      - echo 'Installing node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm install" }

      - echo 'Installing husky pre-commit...'
      - task: _with_nvm
        vars: { COMMAND: "npm run prepare" }

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:init"

  lint:
    desc: Lint project
    cmds:
      - echo 'Running prettier checks...'
      - task: _prettier
        vars: { COMMAND: "--check ." }

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:lint"

  lint-fix:
    desc: Lint fix project
    cmds:
      - echo 'Running prettier fixes...'
      - task: _prettier
        vars: { COMMAND: "--write ." }

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:lint-fix"

  test:
    desc: Test project
    cmds:
      - echo 'Running tests...'

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:test"

  clean:
    desc: Clean project environment
    cmds:
      - echo 'Cleaning node dependencies...'
      - rm -rf {{.NENV}}

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:clean"

  dependencies-update:
    desc: Update dependencies
    cmds:
      - echo 'Updating node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm update" }
      - task: _with_nvm
        vars: { COMMAND: "npm outdated" }
      - task: _with_nvm
        vars: { COMMAND: "npm audit" }

      - for: { var: SERVICES, as: SERVICE }
        task: "{{.SERVICE}}:dependencies-update"

  update-from-template:
    desc: Update project from template
    cmds:
      - echo 'Updating project from template...'
      - cookiecutter
        --no-input
        --overwrite-if-exists
        --output-dir ../
        {{.TEMPLATE_PATH}}
        project_name="DnD Beyond Telegram Bot"
        project_slug="ddbot"
        node_version="v20.15.1"
        owner_name="Dmitry Ovsiannikov"
        owner_github_login="ovsds"
        scripts="false"
        services="ddbot"
    vars:
      TEMPLATE_PATH: '{{.TEMPLATE_PATH | default "https://github.com/ovsds/template-repository"}}'
