app:
  env: development
  debug: true
server:
  host: "0.0.0.0"
  port: 8080
  public_host: "https://${NGROK_DOMAIN}"
telegram:
  token: ${TELEGRAM_TOKEN}
  webhook_secret_token: DEFINITELY_NOT_A_SECRET
context:
  type: redis
  host: ${REDIS_MASTER_HOST}
  port: ${REDIS_MASTER_PORT}
  db: 0
  password: ${REDIS_PASSWORD}
